name: Try to build Angular app

on:
  pull_request:
    paths:
      - 'src/**'
      - '*.js'
    types: [ opened, synchronize, reopened, closed ]

jobs:
  try-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify pnpm-lock.yaml is checked out
        run: |
          if [ ! -f pnpm-lock.yaml ]; then
            echo "Error: pnpm-lock.yaml is missing."
            exit 1
          else
            echo "pnpm-lock.yaml is present."
          fi

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ${{ github.workspace }}

      - name: Install Angular CLI
        run: pnpm install -g @angular/cli

      - name: Build Angular app
        run: pnpm ng build --configuration=production